# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); package_coverage(exclusions = list("R/skprGUI.R","R/skprGUIbrowser.R")); codecov()'